[2024-02-04 09:53:49,547] [6640] [app_log] [authentication_untils.py:35] [authentication_untils:send_sms_to_number] [ERROR]- 发送短信失败，手机号为15865438684，验证码为0247. 原因：
[31m[49mHTTP Error[0m [37m[49mYour request was:[0m

[36m[49mPOST /Accounts/ACd9265533ead59926fa7cff7a262b2991/Messages.json[0m

[37m[49mTwilio returned the following information:[0m

[34m[49mUnable to create record: Permission to send an SMS has not been enabled for the region indicated by the 'To' number: 1586543XXXX[0m

[37m[49mMore information may be available here:[0m

[34m[49mhttps://www.twilio.com/docs/errors/21408[0m


[2024-02-04 09:54:15,185] [4904] [app_log] [authentication_untils.py:35] [authentication_untils:send_sms_to_number] [ERROR]- 发送短信失败，手机号为15863027613，验证码为8356. 原因：
[31m[49mHTTP Error[0m [37m[49mYour request was:[0m

[36m[49mPOST /Accounts/ACd9265533ead59926fa7cff7a262b2991/Messages.json[0m

[37m[49mTwilio returned the following information:[0m

[34m[49mUnable to create record: Permission to send an SMS has not been enabled for the region indicated by the 'To' number: 1586302XXXX[0m

[37m[49mMore information may be available here:[0m

[34m[49mhttps://www.twilio.com/docs/errors/21408[0m


[2024-02-04 10:00:57,749] [13904] [app_log] [authentication_untils.py:35] [authentication_untils:send_sms_to_number] [ERROR]- 发送短信失败，手机号为15863027613，验证码为3896. 原因：
[31m[49mHTTP Error[0m [37m[49mYour request was:[0m

[36m[49mPOST /Accounts/ACd9265533ead59926fa7cff7a262b2991/Messages.json[0m

[37m[49mTwilio returned the following information:[0m

[34m[49mUnable to create record: Invalid From Number (caller ID): +86+12512200453[0m

[37m[49mMore information may be available here:[0m

[34m[49mhttps://www.twilio.com/docs/errors/21212[0m


[2024-02-04 10:01:38,916] [544] [app_log] [authentication_untils.py:32] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为0925
[2024-02-04 10:15:47,391] [8452] [app_log] [authentication_untils.py:43] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为7532
[2024-02-04 10:19:08,925] [25484] [app_log] [authentication_untils.py:46] [authentication_untils:send_sms_to_number] [ERROR]- 发送短信失败，手机号为15863027613，验证码为3570. 原因：
[31m[49mHTTP Error[0m [37m[49mYour request was:[0m

[36m[49mPOST /Accounts/ACd9265533ead59926fa7cff7a262b2991/Messages.json[0m

[37m[49mTwilio returned the following information:[0m

[34m[49mUnable to create record: Permission to send an SMS has not been enabled for the region indicated by the 'To' number: +1 586-302-XXXX[0m

[37m[49mMore information may be available here:[0m

[34m[49mhttps://www.twilio.com/docs/errors/21408[0m


[2024-02-04 11:07:58,486] [18304] [app_log] [authentication_untils.py:44] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为4803
[2024-02-04 11:07:58,486] [18304] [app_log] [authentication_untils.py:48] [authentication_untils:send_sms_to_number] [ERROR]- 发送短信失败，手机号为15863027613，验证码为4803. 原因：'State' object has no attribute 'redis'
[2024-02-04 11:12:11,253] [17068] [app_log] [authentication_untils.py:44] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为1439
[2024-02-04 11:12:13,308] [17068] [app_log] [authentication_untils.py:48] [authentication_untils:send_sms_to_number] [ERROR]- 发送短信失败，手机号为15863027613，验证码为1439. 原因：Client sent AUTH, but no password is set
[2024-02-04 11:15:31,681] [20360] [app_log] [authentication_untils.py:44] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为5438
[2024-02-04 12:57:25,397] [23308] [app_log] [authentication_untils.py:65] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为6574
[2024-02-04 13:05:07,734] [23308] [app_log] [authentication_untils.py:65] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为2361
[2024-02-04 13:10:21,225] [6636] [app_log] [authentication_untils.py:65] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为3401
[2024-02-04 15:00:09,625] [22348] [app_log] [authentication_untils.py:69] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为5984
[2024-02-04 15:00:09,628] [22348] [app_log] [authentication_untils.py:86] [authentication_untils:send_sms_to_number] [ERROR]- 发送短信失败，手机号为15863027613，验证码为5984. 原因：'Depends' object has no attribute 'query'
[2024-02-04 15:07:07,491] [22852] [app_log] [authentication_untils.py:69] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为5173
[2024-02-04 15:07:07,493] [22852] [app_log] [authentication_untils.py:86] [authentication_untils:send_sms_to_number] [ERROR]- 发送短信失败，手机号为15863027613，验证码为5173. 原因：unsupported operand type(s) for +=: 'NoneType' and 'int'
[2024-02-04 15:10:07,856] [15588] [app_log] [authentication_untils.py:69] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为6543
[2024-02-04 15:10:07,857] [15588] [app_log] [authentication_untils.py:87] [authentication_untils:send_sms_to_number] [ERROR]- 发送短信失败，手机号为15863027613，验证码为6543. 原因：unsupported operand type(s) for +=: 'NoneType' and 'int'
[2024-02-04 15:11:02,872] [15824] [app_log] [authentication_untils.py:69] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为2018
[2024-02-04 15:13:35,925] [12516] [app_log] [authentication_untils.py:69] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为2856
[2024-02-04 15:24:58,157] [25176] [app_log] [authentication_untils.py:69] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为3214
[2024-02-04 16:28:34,750] [6884] [app_log] [authentication_untils.py:69] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为6801
[2024-02-04 16:35:19,721] [19284] [app_log] [authentication_untils.py:69] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为3761
