[2024-02-29 10:10:23,861] [16752] [app_log] [authentication_untils.py:86] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为6895
[2024-02-29 10:13:49,829] [16752] [app_log] [authentication_untils.py:90] [authentication_untils:send_sms_to_number] [ERROR]- 发送短信失败，手机号为15206808727，验证码为3708. 原因：
[31m[49mHTTP Error[0m [37m[49mYour request was:[0m

[36m[49mPOST /Accounts/ACd9265533ead59926fa7cff7a262b2991/Messages.json[0m

[37m[49mTwilio returned the following information:[0m

[34m[49mUnable to create record: The number +86 152 0680 XXXX is unverified. Trial accounts cannot send messages to unverified numbers; verify +86 152 0680 XXXX at twilio.com/user/account/phone-numbers/verified, or purchase a Twilio number to send messages to unverified numbers[0m

[37m[49mMore information may be available here:[0m

[34m[49mhttps://www.twilio.com/docs/errors/21608[0m


[2024-02-29 10:44:20,486] [16752] [app_log] [authentication_untils.py:90] [authentication_untils:send_sms_to_number] [ERROR]- 发送短信失败，手机号为15863027613，验证码为1604. 原因：HTTPSConnectionPool(host='api.twilio.com', port=443): Max retries exceeded with url: /2010-04-01/Accounts/ACd9265533ead59926fa7cff7a262b2991/Messages.json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000207BFC85A10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
[2024-02-29 10:46:16,203] [16752] [app_log] [authentication_untils.py:90] [authentication_untils:send_sms_to_number] [ERROR]- 发送短信失败，手机号为15846320578，验证码为4037. 原因：HTTPSConnectionPool(host='api.twilio.com', port=443): Max retries exceeded with url: /2010-04-01/Accounts/ACd9265533ead59926fa7cff7a262b2991/Messages.json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000207C151AA50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
[2024-02-29 10:47:14,404] [16752] [app_log] [authentication_untils.py:90] [authentication_untils:send_sms_to_number] [ERROR]- 发送短信失败，手机号为15863405867，验证码为4706. 原因：HTTPSConnectionPool(host='api.twilio.com', port=443): Max retries exceeded with url: /2010-04-01/Accounts/ACd9265533ead59926fa7cff7a262b2991/Messages.json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000207C1522D10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
[2024-02-29 10:55:35,775] [16752] [app_log] [authentication_untils.py:90] [authentication_untils:send_sms_to_number] [ERROR]- 发送短信失败，手机号为15863405867，验证码为1039. 原因：HTTPSConnectionPool(host='api.twilio.com', port=443): Max retries exceeded with url: /2010-04-01/Accounts/ACd9265533ead59926fa7cff7a262b2991/Messages.json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000207C152D390>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
[2024-02-29 11:01:44,255] [16752] [app_log] [authentication_untils.py:90] [authentication_untils:send_sms_to_number] [ERROR]- 发送短信失败，手机号为15863027613，验证码为7582. 原因：HTTPSConnectionPool(host='api.twilio.com', port=443): Max retries exceeded with url: /2010-04-01/Accounts/ACd9265533ead59926fa7cff7a262b2991/Messages.json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000207C152F390>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
[2024-02-29 11:07:43,727] [20296] [app_log] [authentication_untils.py:86] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为3748
[2024-02-29 11:12:58,453] [10484] [app_log] [authentication_untils.py:86] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为6941
[2024-02-29 11:13:17,568] [10484] [app_log] [authentication_untils.py:86] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为5807
[2024-02-29 11:14:09,335] [10484] [app_log] [authentication_untils.py:90] [authentication_untils:send_sms_to_number] [ERROR]- 发送短信失败，手机号为15863027618，验证码为0864. 原因：
[31m[49mHTTP Error[0m [37m[49mYour request was:[0m

[36m[49mPOST /Accounts/ACd9265533ead59926fa7cff7a262b2991/Messages.json[0m

[37m[49mTwilio returned the following information:[0m

[34m[49mUnable to create record: The number +86 158 6302 XXXX is unverified. Trial accounts cannot send messages to unverified numbers; verify +86 158 6302 XXXX at twilio.com/user/account/phone-numbers/verified, or purchase a Twilio number to send messages to unverified numbers[0m

[37m[49mMore information may be available here:[0m

[34m[49mhttps://www.twilio.com/docs/errors/21608[0m


[2024-02-29 11:15:19,121] [1644] [app_log] [authentication_untils.py:86] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为2730
[2024-02-29 11:16:27,588] [1644] [app_log] [authentication_untils.py:86] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为6302
[2024-02-29 23:45:13,142] [3984] [app_log] [authentication_untils.py:86] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为4860
[2024-02-29 23:49:44,930] [17228] [app_log] [authentication_untils.py:86] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为6781
[2024-02-29 23:52:19,048] [16732] [app_log] [authentication_untils.py:86] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为8017
[2024-02-29 23:54:02,609] [16732] [app_log] [authentication_untils.py:86] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为7564
[2024-02-29 23:54:33,798] [16732] [app_log] [authentication_untils.py:86] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为2941
[2024-02-29 23:54:46,929] [16732] [app_log] [authentication_untils.py:86] [authentication_untils:send_sms_to_number] [INFO]- 发送短信成功，手机号为15863027613，验证码为2431
